import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { LandSaleCard } from '../components'

import { getMetaSigner, getSellItems, SaleItem } from '../data'

import styles from '../styles/Home.module.css'

const numberPerPage = 15

const Home: NextPage = () => {
  const [allLands, setAllLands] = useState<SaleItem[]>([])
  const [lands, setLands] = useState<SaleItem[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(0)
  const [acc, setAcc] = useState('')

  const load = () => {
    (async () => {
      const _lands = await getSellItems()
      setTotal(_lands.length)
      setAllLands(_lands)
      setPage(1)
    })()
  }

  useEffect(() => {
    (async () => {
      const signer = await getMetaSigner()
      setAcc(await signer.getAddress())
    })()
  })

  useEffect(() => {
    if (page > 0 && allLands.length) {
      const start = (page - 1) * numberPerPage
      setLands(allLands.slice(start, start + numberPerPage))
    }
  }, [allLands, page])

  const sortPriceInc = () => {
    setAllLands(allLands.sort((a, b) => a.price - b.price).slice(0))
  }

  const sortPriceDec = () => {
    setAllLands(allLands.sort((a, b) => b.price - a.price).slice(0))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>DVI Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={load}>Load</button>
      <button onClick={() => setPage(page - 1)}>prev</button>
      <button onClick={() => setPage(page + 1)}>next</button>
      <span>{page}</span>
      <button onClick={sortPriceInc}>Price Up</button>
      <button onClick={sortPriceDec}>Price Down</button>
      {acc}

      <div style={{display: 'flex', flexWrap: 'wrap'}}>
      {lands.map(land => (
        <LandSaleCard land={land} key={land.id} />
      ))}
      </div>
    </div>
  )
}

export default Home
