import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext, useEffect, useState } from 'react'

import Button from '@mui/material/Button'
import IconButton from '@mui/material/IconButton'
import { FaArrowLeft, FaArrowRight, FaSortUp, FaSortDown } from 'react-icons/fa'

import { LandSaleCard, MarketContext, CardStatus } from '../components'

import { categorizeItems, getMetaSigner, getPreciousItems, getSellItems, SaleItem } from '../data'

import styles from '../styles/Home.module.css'

const numberPerPage = 15
const items: {[id: number]: CardStatus} = {}

function getItemStatus(id: number): CardStatus {
  return items[id] || CardStatus.Selling
}

const Home: NextPage = () => {
  const [allLands, setAllLands] = useState<SaleItem[]>([])
  const [lands, setLands] = useState<SaleItem[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(0)
  const [acc, setAcc] = useState('')

  const state = useContext(MarketContext)
  items[state.tokenId] = CardStatus.Sold
  if (state.to === acc) {
    items[state.tokenId] = CardStatus.Owned  // owned item
  }

  const load = () => {
    (async () => {
      // const _lands = await getSellItems()
      const _lands = await getPreciousItems()
      setTotal(_lands.length)
      setAllLands(_lands)
      setPage(1)
      // await getPreciousItems()
      // await categorizeItems()
    })()
  }

  useEffect(() => {
    (async () => {
      const signer = await getMetaSigner()
      setAcc(await signer.getAddress())
    })()
  })

  useEffect(() => {
    if (page > 0 && allLands.length) {
      const start = (page - 1) * numberPerPage
      setLands(allLands.slice(start, start + numberPerPage))
    }
  }, [allLands, page])

  const sortPriceInc = () => {
    setAllLands(allLands.sort((a, b) => a.price - b.price).slice(0))
  }

  const sortPriceDec = () => {
    setAllLands(allLands.sort((a, b) => b.price - a.price).slice(0))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>DVI Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button variant='outlined' onClick={load}>Load</Button>
      <IconButton onClick={() => setPage(page - 1)} color="primary">
        <FaArrowLeft/>
      </IconButton>
      <IconButton onClick={() => setPage(page + 1)} color="primary">
        <FaArrowRight/>
      </IconButton>
      <span>{page}</span>
      <IconButton onClick={sortPriceInc}><FaSortUp/></IconButton>
      <IconButton onClick={sortPriceDec}><FaSortDown/></IconButton>
      {acc}

      <div style={{display: 'flex', flexWrap: 'wrap'}}>
      {lands.map(land => (
        <LandSaleCard token={land} key={land.id} paused={state.paused} status={getItemStatus(land.id)} />
      ))}
      </div>
    </div>
  )
}

export default Home
